
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, ttk


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Usuario\Documents\UEL\IEEE\Carteirinha\Tkinter-Designer-master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1365x768")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 768,
    width = 1365,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    682.0,
    384.0,
    image=image_image_1
)

canvas.create_text(
    514.0,
    42.0,
    anchor="nw",
    text="CADASTRO DE USUÁRIOS",
    fill="#FFFFFF",
    font=("Horta", 48 * -1)
)

canvas.create_text(
    67.0,
    172.0,
    anchor="nw",
    text="NOME:",
    fill="#FFFFFF",
    font=("Horta", 48 * -1)
)

canvas.create_text(
    67.0,
    293.0,
    anchor="nw",
    text="N° DE MATRICULA:",
    fill="#FFFFFF",
    font=("Horta", 48 * -1)
)

canvas.create_text(
    67.0,
    426.0,
    anchor="nw",
    text="CURSO",
    fill="#FFFFFF",
    font=("Horta", 48 * -1)
)

canvas.create_text(
    67.0,
    550.0,
    anchor="nw",
    text="EMAIL:",
    fill="#FFFFFF",
    font=("Horta", 48 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Voltar"),
    relief="flat"
)
button_1.place(
    x=33.0,
    y=681.0,
    width=143.0,
    height=47.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    527.5,
    201.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=('Horto 25')
)
entry_1.place(
    x=204.0,
    y=179.0,
    width=647.0,
    height=43.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    560.0,
    322.5,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=('Horto 25')
)
entry_2.place(
    x=374.0,
    y=300.0,
    width=372.0,
    height=43.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    537.5,
    579.5,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=('Horto 25')
)
entry_3.place(
    x=214.0,
    y=557.0,
    width=647.0,
    height=43.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    112.0,
    54.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1253.0,
    54.0,
    image=image_image_3
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Cadastrar"),
    relief="flat"
)
button_2.place(
    x=1012.0,
    y=644.0,
    width=303.0,
    height=84.0
)

def changeMonth():
    comboExample["values"] = ["Engenharia Elétrica", "Ciência da Computação",]
    
comboExample = ttk.Combobox(
    window, values=["Engenharia Elétrica", "Ciência da Computação"], postcommand=changeMonth, font="Horto 25 bold"
)
comboExample.pack()

comboExample.option_add("*TCombobox*Listbox*Font", ("Arial", 16))

comboExample.config(width=21) 
comboExample.place(x=199, y=430)

window.resizable(False, False)
window.mainloop()
