# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import PhotoImage, Canvas, Text, Button, ttk
import sys

from tab_functions import abrir_aba_editar_usuario


ASSETS_PATH = Path(__file__).parent / "assets" / "frame0"
ROOT_PATH = Path(__file__).parent.parent.parent
if str(ROOT_PATH) not in sys.path:
    sys.path.append(str(ROOT_PATH))
from Telas.defs import *


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def criar_tela_consultar_usuarios(
    frame: ttk.Frame,
    imagens: dict[str, dict],
    notebook: ttk.Notebook,
    imagens_dict: dict[str, dict],
):
    # Imagens
    imagens["image_1"] = PhotoImage(file=relative_to_assets("image_1.png"))
    imagens["entry_1"] = PhotoImage(file=relative_to_assets("entry_1.png"))
    imagens["button_1"] = PhotoImage(file=relative_to_assets("button_1.png"))
    imagens["button_2"] = PhotoImage(file=relative_to_assets("button_2.png"))
    imagens["image_2"] = PhotoImage(file=relative_to_assets("image_2.png"))
    imagens["button_3"] = PhotoImage(file=relative_to_assets("button_3.png"))
    imagens["image_3"] = PhotoImage(file=relative_to_assets("image_3.png"))

    # Canvas
    canvas = Canvas(
        frame,
        bg="#FFFFFF",
        height=768,
        width=1365,
        bd=0,
        highlightthickness=0,
        relief="ridge",
    )
    canvas.place(x=0, y=0)

    # Adiciona imagens, textos, retângulos ao canvas
    canvas.create_image(682.0, 384.0, image=imagens["image_1"])
    canvas.create_image(607.5, 83.0, image=imagens["entry_1"])
    canvas.create_rectangle(36.0, 185.0, 1050.0, 251.0, fill="#D9D9D9", outline="")
    canvas.create_rectangle(36.0, 251.0, 1050.0, 735.0, fill="#FFFFFF", outline="")
    canvas.create_rectangle(103.0, 55.0, 1050.0, 112.0, fill="#FFFFFF", outline="")
    canvas.create_image(1211.0, 421.0, image=imagens["image_2"])
    canvas.create_image(135.0, 82.0, image=imagens["image_3"])
    canvas.create_text(
        122.0,
        190.0,
        anchor="nw",
        text="Nome",
        fill="#000000",
        font=(FONTE_TELAS, 48 * -1),
    )
    canvas.create_text(
        512.0,
        191.0,
        anchor="nw",
        text="Matrícula",
        fill="#000000",
        font=(FONTE_TELAS, 48 * -1),
    )
    canvas.create_text(
        885.0,
        190.0,
        anchor="nw",
        text="Ação",
        fill="#000000",
        font=(FONTE_TELAS, 48 * -1),
    )
    canvas.create_text(
        36.0,
        142.0,
        anchor="nw",
        text="Lista de usuários:",
        fill="#FFFFFF",
        font=(FONTE_TELAS, 40 * -1),
    )

    # Entrada de texto
    entry_1 = Text(
        frame,
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0,
        font=(FONTE_INPUT, 28),
    )
    entry_1.place(x=174.0, y=60.0, width=867.0, height=44.0)
    
    # Botões
    button_1 = Button(
        frame,
        image=imagens["button_1"],
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("Deletar"),
        relief="flat",
    )
    button_1.place(x=1076.0, y=651.0, width=268.0, height=68.0)

    button_2 = Button(
        frame,
        image=imagens["button_2"],
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("Pesquisar"),
        relief="flat",
    )
    button_2.place(x=1124.0, y=55.0, width=176.0, height=60.0)

    button_3 = Button(
        frame,
        image=imagens["button_3"],
        borderwidth=0,
        highlightthickness=0,
        command=lambda: abrir_aba_editar_usuario(notebook,imagens_dict),
        relief="flat",
    )
    button_3.place(x=859.0, y=275.0, width=138.0, height=49.0)


# imagens = {}
# window = Tk()
# window.geometry(TAMANHO_JANELA)
# window.configure(bg="#FFFFFF")
# cria_tela_consultar_usuarios(window, imagens)
# window.mainloop()
