# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, ttk
from ttkbootstrap import DateEntry
import tkinter as tk
import sys


ASSETS_PATH = Path(__file__).parent / "assets" / "frame0"
ROOT_PATH = Path(__file__).parent.parent.parent
if str(ROOT_PATH) not in sys.path:
    sys.path.append(str(ROOT_PATH))
from Telas.defs import *
from tab_functions import abrir_aba_editar_rg


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def criar_tela_buscar_rg(
    frame: ttk.Frame,
    imagens: dict[str, dict],
    notebook: ttk.Notebook,
    imagens_dict: dict[str, dict],
):
    # Imagens
    imagens["image_1"] = PhotoImage(file=relative_to_assets("image_1.png"))
    imagens["image_2"] = PhotoImage(file=relative_to_assets("image_2.png"))
    imagens["button_1"] = PhotoImage(file=relative_to_assets("button_1.png"))
    imagens["button_2"] = PhotoImage(file=relative_to_assets("button_2.png"))

    # Canvas
    canvas = Canvas(
        frame,
        bg="#FFFFFF",
        height=768,
        width=1365,
        bd=0,
        highlightthickness=0,
        relief="ridge",
    )
    canvas.place(x=0, y=0)

    # Adiciona imagens, textos, retângulos ao canvas
    canvas.create_image(682.0, 384.0, image=imagens["image_1"])
    canvas.create_image(682.0, 520.0, image=imagens["image_2"])
    canvas.create_text(
        80.0,
        60.0,
        anchor="nw",
        text="Data:",
        fill="#FFFFFF",
        font=(FONTE_TELAS, 48 * -1),
    )
    canvas.create_rectangle(70.0, 190.0, 1084.0, 256.0, fill="#D9D9D9", outline="")
    canvas.create_rectangle(70.0, 256.0, 1084.0, 322.0, fill="#FFFFFF", outline="")
    canvas.create_text(
        156.0,
        195.0,
        anchor="nw",
        text="Data",
        fill="#000000",
        font=(FONTE_TELAS, 48 * -1),
    )
    canvas.create_text(
        450.0,
        195.0,
        anchor="nw",
        text="N° de presenças",
        fill="#000000",
        font=(FONTE_TELAS, 48 * -1),
    )
    canvas.create_text(
        872.0,
        195.0,
        anchor="nw",
        text="Ações",
        fill="#000000",
        font=(FONTE_TELAS, 48 * -1),
    )

    data_var = tk.StringVar()

    # Input data
    input_data = DateEntry(master=frame, dateformat="%d/%m/%Y")
    input_data.entry.config(textvariable=data_var)
    input_data.place(x=180.0, y=80.0)

    # Botões
    button_1 = Button(
        frame,
        image=imagens["button_1"],
        borderwidth=0,
        highlightthickness=0,
        command=lambda: abrir_aba_editar_rg(notebook, imagens_dict),
        relief="flat",
    )
    button_1.place(x=855.0, y=262.0, width=138.0, height=49.0)

    button_2 = Button(
        frame,
        image=imagens["button_2"],
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print(data_var.get()),
        relief="flat",
    )
    button_2.place(x=610.0, y=58.0, width=164.0, height=69.0)
