
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / "assets" / "frame0"


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1365x768")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 768,
    width = 1365,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    682.0,
    384.0,
    image=image_image_1
)

canvas.create_rectangle(
    36.0,
    185.0,
    1050.0,
    251.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    36.0,
    251.0,
    1050.0,
    735.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    122.0,
    190.0,
    anchor="nw",
    text="Nome",
    fill="#000000",
    font=("Horta", 48 * -1)
)

canvas.create_text(
    514.0,
    191.0,
    anchor="nw",
    text="Curso",
    fill="#000000",
    font=("Horta", 48 * -1)
)

canvas.create_text(
    838.0,
    190.0,
    anchor="nw",
    text="Presente",
    fill="#000000",
    font=("Horta", 48 * -1)
)

canvas.create_text(
    81.0,
    57.0,
    anchor="nw",
    text="Data:",
    fill="#FFFFFF",
    font=("Horta", 48 * -1)
)

canvas.create_rectangle(
    180.0,
    67.0,
    381.0,
    112.0,
    fill="#FFFFFF",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    289.0,
    92.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=('Courierprime 20')
)
entry_1.place(
    x=208.0,
    y=77.0,
    width=162.0,
    height=28.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Salvar RG"),
    relief="flat"
)
button_1.place(
    x=1154.0,
    y=342.0,
    width=170.0,
    height=68.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Deletar RG"),
    relief="flat"
)
button_2.place(
    x=1154.0,
    y=486.0,
    width=170.0,
    height=68.0
)

canvas.create_text(
    36.0,
    142.0,
    anchor="nw",
    text="Lista de usuários:",
    fill="#FFFFFF",
    font=("Horta", 40 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    1238.0,
    120.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
